### ISSUE TITLE
Responsive Behaviour not being shown in Toggle Buttons

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/Tribute-Page#1]
**Current Mobile View** 
![screenshot** from 2018-03-18 01-11-28](https://user-images.githubusercontent.com/13948542/37559317-bc116d8a-2a49-11e8-9e53-dbe7fcd17c92.png)

**Current Desktop View**
![screenshot from 2018-03-18 01-11-45](https://user-images.githubusercontent.com/13948542/37559318-bcac09b2-2a49-11e8-855d-c1759a5da3a5.png)

**Expected View**
Toggle Button must be vertically aligned as Center with the current display image in all the possible viewports.

**Comment by puneetpalkaur** [comment]
Fixed, waiting on pull request

**Comment by jaykay12** [comment]
Resolved by @puneetpalkaur with #7
